// AES-256-GCM encryption for OAuth refresh tokens at rest.
// Stored blob layout: iv(12) || authTag(16) || ciphertext.
// Key from TOKEN_ENCRYPTION_KEY (32-byte, base64 or hex). In prod it lives in
// /opt/irises/.env on the VM (auto-generated by deploy/vm-bootstrap.sh).
import { createCipheriv, createDecipheriv, randomBytes } from 'node:crypto';

function loadKey(): Buffer {
  const raw = process.env.TOKEN_ENCRYPTION_KEY;
  if (!raw) {
    throw new Error('TOKEN_ENCRYPTION_KEY not set — required to encrypt Gmail tokens');
  }
  // Accept base64 or hex; must decode to 32 bytes.
  let key = Buffer.from(raw, 'base64');
  if (key.length !== 32) key = Buffer.from(raw, 'hex');
  if (key.length !== 32) {
    throw new Error('TOKEN_ENCRYPTION_KEY must decode to 32 bytes (base64 or hex)');
  }
  return key;
}

export function encryptToken(plaintext: string): Buffer {
  const iv = randomBytes(12);
  const cipher = createCipheriv('aes-256-gcm', loadKey(), iv);
  const enc = Buffer.concat([cipher.update(plaintext, 'utf8'), cipher.final()]);
  const tag = cipher.getAuthTag();
  return Buffer.concat([iv, tag, enc]);
}

export function decryptToken(blob: Buffer): string {
  const iv = blob.subarray(0, 12);
  const tag = blob.subarray(12, 28);
  const data = blob.subarray(28);
  const decipher = createDecipheriv('aes-256-gcm', loadKey(), iv);
  decipher.setAuthTag(tag);
  return Buffer.concat([decipher.update(data), decipher.final()]).toString('utf8');
}
