// The proactive inbound door: the ENGINE's cron jobs (reminders, mail nudges, anything the user
// scheduled through Irises) deliver their outcome here, and Irises voices it to the chat in its
// own tone. The engine owns scheduling and email — the engine
// does the work and the scheduling; Irises stays the mouth.
//
// This router is only the DOOR: validation, auth, the size cap, and an immediate 202. Identity
// resolution, idempotency, quiet hours and the voicing itself all live behind the injected
// `deliver` (src/pipeline/proactiveDelivery.ts), shared with the update announcer.
//
// Auth mirrors the web-channel convention (routes.ts): ENGINE_PUSH_TOKEN set → the x-engine-token
// header must match exactly; unset → loopback-only. The token is generated by
// scripts/engine-setup.sh and handed to the engine's job environment — treat it like a credential
// (it can make Irises speak).
import { Router, type Request } from 'express';
import { resolveChannel } from '../channels/registry.js';
import { record } from '../diagnostics/trace.js';
import type { ProactiveMessage, ProactiveOutcome, ProactiveEmailMeta } from '../pipeline/proactiveDelivery.js';

const MAX_TEXT_CHARS = 4000;
const MAX_KEY_CHARS = 200;
const MAX_META_CHARS = 200;

export type PushKind = 'reminder' | 'email' | 'memo';

// Exact match, never a substring: `includes('127.0.0.1')` also accepts a real remote address that
// merely CONTAINS the loopback text, and the tokenless mode is the dev fallback that guards a door
// which can make Irises speak.
const LOOPBACK = new Set(['127.0.0.1', '::1', '::ffff:127.0.0.1']);

function authorized(req: Request): boolean {
  const token = process.env.ENGINE_PUSH_TOKEN;
  if (token) return req.headers['x-engine-token'] === token;
  return LOOPBACK.has(req.ip || req.socket.remoteAddress || '');
}

function str(v: unknown, cap: number): string | undefined {
  if (typeof v !== 'string') return undefined;
  const s = v.trim();
  return s ? s.slice(0, cap) : undefined;
}

/** Whitelist, never a passthrough: the engine's job author can put anything in `meta`, and these
 *  four fields are the only ones that reach memory. */
function readMeta(raw: unknown): ProactiveEmailMeta | undefined {
  if (!raw || typeof raw !== 'object') return undefined;
  const src = raw as Record<string, unknown>;
  const meta: ProactiveEmailMeta = {};
  for (const key of ['from', 'subject', 'deadlineDate', 'deadlineLabel'] as const) {
    const v = str(src[key], MAX_META_CHARS);
    if (v) meta[key] = v;
  }
  return Object.keys(meta).length ? meta : undefined;
}

export function createEnginePushRouter(deps: { deliver: (msg: ProactiveMessage) => Promise<ProactiveOutcome> }): Router {
  const router = Router();

  router.post('/api/engine/push', async (req, res) => {
    if (!authorized(req)) {
      res.status(403).json({ error: 'forbidden — send x-engine-token' });
      return;
    }
    const chatId = typeof req.body?.chatId === 'string' ? req.body.chatId.trim() : '';
    const rawText = typeof req.body?.text === 'string' ? req.body.text.trim() : '';
    const kind: PushKind = req.body?.kind === 'email' || req.body?.kind === 'memo' ? req.body.kind : 'reminder';
    if (!chatId || !rawText) {
      res.status(400).json({ error: 'chatId and text are required' });
      return;
    }
    // Only chats a registered channel can actually reach — an unknown prefix or unregistered
    // channel is a config error on the engine side, surfaced hard so the job author notices.
    try {
      resolveChannel(chatId);
    } catch (err) {
      res.status(400).json({ error: (err as Error).message });
      return;
    }
    const text = rawText.slice(0, MAX_TEXT_CHARS);
    // The engine's own idempotency key when it sends one (a job id, a message id) — otherwise the
    // pipeline hashes chatId|kind|text, which already collapses a retried identical push.
    const dedupeKey = str(req.body?.dedupeKey, MAX_KEY_CHARS);
    const emailMeta = readMeta(req.body?.meta);
    record({ type: 'event', chatId, label: 'engine:push', detail: { kind, chars: text.length, ...(dedupeKey ? { dedupeKey } : {}) } });
    // 202 immediately — voicing + the per-chat mouth queue happen after the engine's HTTP call is
    // done (its cron job shouldn't hang on our LLM latency). The delivery path relays `text` exactly
    // and degrades through Fallfirm to its hardcoded floor if the voicer model is unavailable, so the
    // push always lands. The engine RETRYING because it never saw this 202 is exactly what the
    // dedupe window absorbs.
    res.status(202).json({ ok: true, chatId });
    try {
      const outcome = await deps.deliver({ chatId, kind, text, ...(dedupeKey ? { dedupeKey } : {}), ...(emailMeta ? { emailMeta } : {}) });
      if (outcome === 'deferred') {
        record({ type: 'event', chatId, label: 'engine:push-deferred', detail: { kind } });
      } else if (outcome === 'duplicate') {
        record({ type: 'event', chatId, label: 'engine:push-duplicate', detail: { kind, ...(dedupeKey ? { dedupeKey } : {}) } });
      } else if (outcome === 'failed') {
        record({ type: 'event', chatId, label: 'engine:push-failed', detail: { kind } });
      } else {
        record({ type: 'event', chatId, label: 'engine:push-delivered', detail: { kind, delivery: outcome } });
      }
    } catch (err) {
      console.error('[enginePush] delivery failed', err);
      record({ type: 'event', chatId, label: 'engine:push-failed', detail: { kind, error: String((err as Error)?.message ?? err) } });
    }
  });

  return router;
}
