// The proactive inbound door: the ENGINE's cron jobs (reminders, mail nudges, anything the user
// scheduled through Irises) deliver their outcome here, and Irises voices it to the chat in its
// own tone. The engine owns scheduling and email — the engine
// does the work and the scheduling; Irises stays the mouth.
//
// Auth mirrors the web-channel convention (routes.ts): ENGINE_PUSH_TOKEN set → the x-engine-token
// header must match exactly; unset → loopback-only. The token is generated by
// scripts/engine-setup.sh and handed to the engine's job environment — treat it like a credential
// (it can make Irises speak).
import { Router, type Request } from 'express';
import { resolveChannel } from '../channels/registry.js';
import { voiceOutcome } from '../agents/fallfirm/client.js';
import { record } from '../diagnostics/trace.js';
import type { SendFollowUp } from '../agents/orchestrator.js';

const MAX_TEXT_CHARS = 4000;

export type PushKind = 'reminder' | 'email' | 'memo';

function authorized(req: Request): boolean {
  const token = process.env.ENGINE_PUSH_TOKEN;
  if (token) return req.headers['x-engine-token'] === token;
  const ip = req.ip || req.socket.remoteAddress || '';
  return ip.includes('127.0.0.1') || ip.includes('::1');
}

/** How Fallfirm frames each push kind — the substance (facts) is relayed exactly, the framing is
 *  Irises reaching out on its own, never "my engine told me to tell you". */
function outcomeFor(kind: PushKind, text: string) {
  const framing: Record<PushKind, string> = {
    reminder: 'a reminder they set with you is due — deliver it now, warm and brief, like you remembered on your own',
    email: 'something just landed in their email that they asked you to watch for — surface it now, brief and useful',
    memo: 'you have something for them from work you were doing in the background — hand it over naturally',
  };
  return { kind: 'confirmed' as const, summary: framing[kind], facts: text };
}

export function createEnginePushRouter(deps: { sendFollowUp: SendFollowUp }): Router {
  const router = Router();

  router.post('/api/engine/push', async (req, res) => {
    if (!authorized(req)) {
      res.status(403).json({ error: 'forbidden — send x-engine-token' });
      return;
    }
    const chatId = typeof req.body?.chatId === 'string' ? req.body.chatId.trim() : '';
    const rawText = typeof req.body?.text === 'string' ? req.body.text.trim() : '';
    const kind: PushKind = req.body?.kind === 'email' || req.body?.kind === 'memo' ? req.body.kind : 'reminder';
    if (!chatId || !rawText) {
      res.status(400).json({ error: 'chatId and text are required' });
      return;
    }
    // Only chats a registered channel can actually reach — an unknown prefix or unregistered
    // channel is a config error on the engine side, surfaced hard so the job author notices.
    try {
      resolveChannel(chatId);
    } catch (err) {
      res.status(400).json({ error: (err as Error).message });
      return;
    }
    const text = rawText.slice(0, MAX_TEXT_CHARS);
    record({ type: 'event', chatId, label: 'engine:push', detail: { kind, chars: text.length } });
    // 202 immediately — voicing + the per-chat mouth queue happen after the engine's HTTP call is
    // done (its cron job shouldn't hang on our LLM latency). voiceOutcome relays `facts` exactly
    // and drops to its hardcoded floor if the voicer model is unavailable, so the push always lands.
    res.status(202).json({ ok: true, chatId });
    try {
      const delivery = await deps.sendFollowUp(chatId, () => voiceOutcome(outcomeFor(kind, text), chatId, ''), {});
      record({ type: 'event', chatId, label: 'engine:push-delivered', detail: { kind, delivery } });
    } catch (err) {
      console.error('[enginePush] delivery failed', err);
      record({ type: 'event', chatId, label: 'engine:push-failed', detail: { kind, error: String((err as Error)?.message ?? err) } });
    }
  });

  return router;
}
